apiVersion: v1
kind: Service
metadata:
  labels:
    app: hellogo
  name: hellogo
spec:
  ports:
  - name: http-hellogo
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hellogo
